FROM node:18-alpine3.16

WORKDIR /home/services/notification-service

COPY ../../package.json .

COPY ../../yarn.lock .

RUN yarn install

COPY ../.. ./

RUN npx prisma generate


CMD ["yarn", "start:dev"]